# Generated by Django 2.0.5 on 2018-09-04 23:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='user/%Y/%m/%d/')),
                ('updated', models.BooleanField(default=False)),
                ('description', models.TextField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField(blank=True, default='', null=True)),
                ('room_street', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_apt', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_zip', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_price', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), size=8)),
                ('room_spaces', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), size=8)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='air.Profile')),
            ],
        ),
    ]
