# Generated by Django 2.0.5 on 2018-09-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0004_auto_20180905_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile',
            field=models.ForeignKey(blank=True, default='1910231502357422', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='air.Profile'),
        ),
    ]
