# Generated by Django 2.0.5 on 2018-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0006_auto_20180905_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
