# Generated by Django 2.0.5 on 2018-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0007_auto_20180905_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_country',
            field=models.CharField(blank=True, default='United States', max_length=100, null=True),
        ),
    ]
