# Generated by Django 2.0.5 on 2018-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0009_auto_20180906_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, default='room_pic/default-room.png', null=True, upload_to='room_pic/'),
        ),
    ]
