# Generated by Django 2.0.5 on 2018-09-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0010_room_room_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, default='pic_folder/default-room.png', null=True, upload_to='pic_folder/'),
        ),
    ]
